package betfair.pages;


import org.openqa.selenium.support.PageFactory;
import org.testng.ITestResult;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import betfair.util.Helpers;



public class G25 extends TestBase{

	Login login;
	Tabs tabs;
	AdminNavigationTree adminNavigation;
	AdminEventSelectionCriteria adminEventSelection;
	AdminEventCreation adminEvent;
	AdminMarketCreation adminMarket;
	AdminSelectionCreation adminSelection;
	AdminDelete adminDelete;

	@BeforeClass
	public void classInit() {
		webDriver.get(websiteUrl);
		login = PageFactory.initElements(webDriver, Login.class);
		tabs = PageFactory.initElements(webDriver, Tabs.class);
		adminNavigation = PageFactory.initElements(webDriver, AdminNavigationTree.class);
		adminEvent = PageFactory.initElements(webDriver, AdminEventCreation.class);
		adminMarket = PageFactory.initElements(webDriver, AdminMarketCreation.class);
		adminSelection = PageFactory.initElements(webDriver, AdminSelectionCreation.class);
		adminEventSelection = PageFactory.initElements(webDriver, AdminEventSelectionCriteria.class);
		adminDelete = PageFactory.initElements(webDriver, AdminDelete.class);
	}

	@BeforeMethod(description = "Logs in before method")
	public void login() {
		login.typeUsername();
		login.typePassword();
		login.clickLogin();
	}
	
	@Test(description ="Create 25 English Football Events")
	public void createEnglishFootballEvents() {
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness1");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness2");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness3");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness4");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness5");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness6");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness7");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness8");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness9");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness10");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness11");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness12");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness13");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness14");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness15");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness16");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness17");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness18");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness19");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness20");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness21");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness22");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness23");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness24");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("English Football");
		adminEventSelection.selectType("Npower League Two");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName("harness25");
		adminEvent.insertStartTime(Helpers.getDateWithOffsetInYears(1));
		adminEvent.clickAddEvent();
		adminMarket.selectMarket("|Match Odds|");
		adminMarket.clickAddEventMarket();
		adminMarket.selectDisplayed("Yes");
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("home");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("away");
		adminSelection.selectLocation("away");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("draw");
		adminSelection.selectLocation("draw");
		adminSelection.enterFixedPrice("1/2");
		adminSelection.clickAddFinalSelection();
		
	}
	
	@AfterMethod(description = "Logs out after method")
	public void logout(ITestResult result){
		setScreenshot(result);
		tabs.clickLogout();

	}
	
}