package betfair.pages;

import org.openqa.selenium.support.PageFactory;
import org.testng.Assert;
import org.testng.ITestResult;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import betfair.util.Helpers;

public class SettleWinTest extends TestBase{

	Login login;
	Tabs tabs;
	CampaignManagerTree campaignManagerTree;
	CMOfferSearch cmOfferSearch;
	CMOfferList cmOfferList;
	CMAddOffer cmAddOffer;
	CMAddTrigger cmAddTrigger;
	CMAddReward cmAddReward;
	AdminEventCreation adminEvent;
	CMAddLevel cmAddLevel;
	AdminNavigationTree adminNavigation;
	AdminEventSelectionCriteria adminEventSelection;
	AdminMarketCreation adminMarket;
	AdminSelectionCreation adminSelection;
	AdminEventSettle adminEventSettle;
	AdminEventUnsettle adminEventUnsettle;
	AdminDelete adminDelete;

	@BeforeClass
	public void classInit() {
		webDriver.get(websiteUrl);
		login = PageFactory.initElements(webDriver, Login.class);
		tabs = PageFactory.initElements(webDriver, Tabs.class);
		campaignManagerTree = PageFactory.initElements(webDriver, CampaignManagerTree.class);
		cmOfferSearch = PageFactory.initElements(webDriver, CMOfferSearch.class);
		cmOfferList = PageFactory.initElements(webDriver, CMOfferList.class);
		cmAddOffer = PageFactory.initElements(webDriver, CMAddOffer.class);
		cmAddTrigger = PageFactory.initElements(webDriver, CMAddTrigger.class);
		cmAddReward = PageFactory.initElements(webDriver, CMAddReward.class);
		adminEvent = PageFactory.initElements(webDriver, AdminEventCreation.class);
		cmAddLevel = PageFactory.initElements(webDriver, CMAddLevel.class);
		adminNavigation = PageFactory.initElements(webDriver, AdminNavigationTree.class);
		adminEvent = PageFactory.initElements(webDriver, AdminEventCreation.class);
		adminMarket = PageFactory.initElements(webDriver, AdminMarketCreation.class);
		adminSelection = PageFactory.initElements(webDriver, AdminSelectionCreation.class);
		adminEventSelection = PageFactory.initElements(webDriver, AdminEventSelectionCriteria.class);
		adminEventSettle = PageFactory.initElements(webDriver, AdminEventSettle.class);
		adminEventUnsettle = PageFactory.initElements(webDriver, AdminEventUnsettle.class);
		adminDelete = PageFactory.initElements(webDriver, AdminDelete.class);
	}
	
	@BeforeMethod
	public void loginAdministrator(){
		login.typeUsername();
		login.typePassword();
		login.clickLogin();
		tabs.clickCM();
	}
	
	@AfterMethod
	public void logoutAdministrator(ITestResult result){
		setScreenshot(result);
		tabs.clickLogout();
	}

	@Test(description = "C219091 Registration Trigger")
	public void settleWin() throws Exception {
		String tomorrow = Helpers.getDateWithOffsetInDays(1);
		String today = Helpers.getDateWithOffsetInMinutes(-178);
		String dayAfterTomorrow = Helpers.getDateWithOffsetInDays(2);
		logger.info("Clicking Offers from the Campaign Manager Menu");
		campaignManagerTree.clickOffers();
		logger.info("Clicking the Offers subsection from the Offers option");
		campaignManagerTree.clickOffer();
		logger.info("Clicking Add Offer from the Search Page");
		cmOfferSearch.clickAddOffer();
		logger.info("Entering the Offer Name");
		cmAddOffer.offerName("settleWins");
		logger.info("Selecting currencies");
		cmAddOffer.selAllCurr();
		logger.info("Selecting languages");
		cmAddOffer.selAllLang();
		logger.info("Selecting countries");
		cmAddOffer.selAllCountries();
		logger.info("Entering Entry Date");
		cmAddOffer.entryDate(tomorrow);
		logger.info("Entering end date");
		cmAddOffer.endDate(dayAfterTomorrow);
		logger.info("Entering start date");
		cmAddOffer.startDate(today);
		logger.info("Adding the new offer");
		cmAddOffer.addNewOffer();
		logger.info("Click on Add Trigger");
		cmAddOffer.addTriggers();
		logger.info("Selecting the trigger type");
		cmAddTrigger.typeTrigger("Generic Bet Trigger");
		logger.info("Inserting the trigger currency values");
		cmAddTrigger.insertCurrency("AUD", "1.00");
		cmAddTrigger.insertCurrency("CAD", "1.00");
		cmAddTrigger.insertCurrency("DKK", "1.00");
		cmAddTrigger.insertCurrency("EUR", "1.00");
		cmAddTrigger.insertCurrency("GBP", "1.00");
		cmAddTrigger.insertCurrency("HKD", "1.00");
		cmAddTrigger.insertCurrency("NOK", "1.00");
		cmAddTrigger.insertCurrency("SEK", "1.00");
		cmAddTrigger.insertCurrency("SGD", "1.00");
		cmAddTrigger.insertCurrency("USD", "1.00");
		logger.info("Adding the bet type");
		cmAddTrigger.betTypes("Single");
		logger.info("Click on Add Trigger");
	    cmAddTrigger.addTrigger();
	    logger.info("Click on Add Level");
		cmAddTrigger.addLevel();
		Helpers.switchToWindow(webDriver,2);
		Helpers.resizeWindow(webDriver, 900, 880);
		logger.info("Click on Horse Racing");		
		cmAddLevel.horseRacing();
		Helpers.closeSwitched(webDriver);
	    logger.info("Returning to the offer page");
	    cmAddTrigger.backTrigger();
	    logger.info("Adding the cust group trigger");
	    cmAddOffer.addTriggers();
	    logger.info("Selecting the trigger type");
	    cmAddTrigger.typeTrigger("Settle win");
	    logger.info("Inserting the trigger currency values");
		cmAddTrigger.insertCurrency("AUD", "1.00");
		cmAddTrigger.insertCurrency("CAD", "1.00");
		cmAddTrigger.insertCurrency("DKK", "1.00");
		cmAddTrigger.insertCurrency("EUR", "1.00");
		cmAddTrigger.insertCurrency("GBP", "1.00");
		cmAddTrigger.insertCurrency("HKD", "1.00");
		cmAddTrigger.insertCurrency("NOK", "1.00");
		cmAddTrigger.insertCurrency("SEK", "1.00");
		cmAddTrigger.insertCurrency("SGD", "1.00");
		cmAddTrigger.insertCurrency("USD", "1.00");
		cmAddTrigger.selAllTypes();
	    logger.info("Adding the trigger");
	    cmAddTrigger.addTrigger();
	    logger.info("Click on Add Level");
		cmAddTrigger.addLevel();
		Helpers.switchToWindow(webDriver,2);
		Helpers.resizeWindow(webDriver, 900, 880);
		logger.info("Click on Horse Racing");		
		cmAddLevel.horseRacing();
		Helpers.closeSwitched(webDriver);
	    logger.info("Clicking on Back");
	    cmAddTrigger.backTrigger();
	    cmAddOffer.addTriggers();
	    cmAddTrigger.typeTrigger("Manual Trigger");
	    cmAddTrigger.addTrigger();
	    cmAddTrigger.backTrigger();
	    logger.info("Click on Add Reward");
	    cmAddOffer.addReward();
	    logger.info("Inserting the currency reward values");
	    cmAddReward.insertCurrency("AUD", "10.00");
	    cmAddReward.insertCurrency("CAD", "10.00");
	    cmAddReward.insertCurrency("DKK", "10.00");
	    cmAddReward.insertCurrency("EUR", "10.00");
	    cmAddReward.insertCurrency("GBP", "10.00");
	    cmAddReward.insertCurrency("HKD", "10.00");
	    cmAddReward.insertCurrency("NOK", "10.00");
	    cmAddReward.insertCurrency("SEK", "10.00");
	    cmAddReward.insertCurrency("SGD", "10.00");
	    cmAddReward.insertCurrency("USD", "10.00");
	    logger.info("Entering the Relative Expiry value");
	    cmAddReward.relativeExpiry("01 00:00");
	    logger.info("Selecting the bet type");
	    cmAddReward.selAllReward();
	    logger.info("Click on insert reward");
	    cmAddReward.insertReward();
	    logger.info("Click on Add Redemption");
	    cmAddReward.addRedemption();
	    logger.info("Click on Any");
	    cmAddReward.any();
	    logger.info("Returning to the offer page");
	    cmAddReward.backReward();
	    logger.info("Waiting for the offer to start");
	    Thread.sleep(60000);
		String toCompare = "Settlement results";
		tabs.clickAdmin();
		adminNavigation.clickBettingSetup();
		adminNavigation.clickEvents();
		adminEventSelection.selectClass("Horse Racing");
		adminEventSelection.selectType("Bath");
		adminEventSelection.clickAddEvent();
		adminEvent.insertEventName(adminEvent.randomName());
		adminEvent.insertStartTime("2016-01-01 00:00:00");
		adminEvent.clickAddEvent();
		adminMarket.clickAddEventMarket();
		adminEvent.clickAddMarket();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("H1");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminEventSettle.clickFirstSelection();
		String eventid = adminSelection.getEventid();
		adminSelection.clickModify();
		cmAddOffer.acceptAlert();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("H2");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		adminMarket.clickAddSelection();
		adminSelection.enterDescription("H3");
		adminSelection.enterFixedPrice("3/1");
		adminSelection.clickAddFinalSelection();
		String ssoid = Helpers.getSsoidForClient("90001");
		oxi.call("reqBet").withParams("user:openbet,pass:0p3nb3t,ssoid:"+ssoid+",outcome:"+eventid);
		adminEventSettle.clickFirstSelection();
		adminEventSettle.selectResult("Win");
		adminEventSettle.insertPlace("1");
		adminEventSettle.clickSetResults();
		adminEventSettle.clickSecondSelection();
		adminEventSettle.selectResult("Lose");
		adminEventSettle.insertPlace("2");
		adminEventSettle.clickSetResults();
		adminEventSettle.clickThirdSelection();
		adminEventSettle.selectResult("Void");
		adminEventSettle.clickSetResults();
		adminEventSettle.clickConfirmResults();
		adminEventSettle.clickSettleMarket();
		logger.info("Settled");
		Assert.assertEquals(adminEventSettle.settlementResults(), toCompare);
		tabs.clickCM();
		logger.info("Clicking Offers from the Campaign Manager Menu");
		campaignManagerTree.clickOffers();
		logger.info("Clicking the Offers subsection from the Offers option");
		campaignManagerTree.clickOffer();
		cmOfferSearch.offerSearchName("settleWins");
		cmOfferSearch.clickSearchOffer();
		cmOfferList.offerListName();
		cmAddOffer.manual();
		cmAddTrigger.fire();
		logger.info("Sending the reqAcctGetFreebet request and Filtering the freebetID");
		String outcome="2015333";
		String reqAcctGetFFreebets = oxiLatest.call("reqAcctGetFFreebets").withParams("user:Administrator,pass:1ncharge,ssoid:"+ssoid).withSingleReturn("oxip.response.respAccountGetFreebets.freebetToken.freebetTokenId");
		String reqBetPlaceWithFreeline = oxi.call("reqBetPlaceWithFreeline").withParams("user:Administrator,pass:1ncharge,ssoid:"+ssoid+",outcome:"+outcome+",freebetTokenId:"+reqAcctGetFFreebets).withSingleReturn("oxip.response.returnStatus.message");
		Assert.assertEquals(reqBetPlaceWithFreeline, "success");
		logger.info("Received success response");
	}
	
}
